
  account: HDFEYMR-TIGERANALYTICS_PARTNER
  user: jayaprasanna.gan@tigeranalytics.com
  password: xxxxxxxx
  authenticator: externalbrowser
  role: DWHBI_DEVELOPER
  warehouse: DWHBI_DEVELOPER_WH
  database: TEST_SNOWCONVERT_MSSQL
  schema: public